{% set name = "fcsparser" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fcsparser-{{ version }}.tar.gz
  sha256: df0436bf678df1f4ad3274e55fa06773f884fa45d8329015913a6178d10c73ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pandas >=1.5.3
    - numpy >=1.0.0,<2.0.0

test:
  imports:
    - fcsparser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/eyurtsev/fcsparser
  summary: A python package for reading raw fcs files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - berombau
